import type { Metadata } from "next";
import "./globals.css";
import BackHomeButton from "./components/BackHomeButton";
import MobileSidebarWrapper from "./components/MobileSidebarWrapper";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-Hant" className={cn("h-full antialiased", "font-sans", geist.variable)}>
      <body className="min-h-full">
      <div className=" bg-[#F2F6FF] w-screen h-screen overflow-y-auto flex flex-col sm:flex-row  gap-5 p-4 sm:p-8">
          <div className="bg-[#FBFCFE] rounded-2xl min-w-[250px] w-full sm:w-[250px] h-auto justify-start items-center flex flex-col  overflow-x-hidden shadow-sm shadow-blue-500/20 ">
              <MobileSidebarWrapper />
            </div>
          <div className="w-full h-full flex sm:flex-1 min-w-[250px] bg-[#FBFCFE] rounded-2xl shadow-sm shadow-blue-500/20 overflow-hidden relative">
              {children}
          </div>
          
      </div>
      </body>
    </html>
  );
}
