import type { Metadata } from "next";
import "./globals.css";
import BackHomeButton from "./components/BackHomeButton";
import SideBar from "./components/SideBar";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-Hant" className={cn("h-full antialiased", "font-sans", geist.variable)}>
      <body className="min-h-full">
      <div className=" bg-[#F1F1F1] w-screen h-screen overflow-y-auto flex flex-col sm:flex-row  gap-5 p-4 sm:p-8">
          <div className="bg-[#FBFCFE] rounded-2xl min-w-[250px] w-full sm:w-[250px] h-auto justify-start items-center flex flex-col p-[24px] pt-[24px] overflow-x-hidden shadow-sm shadow-blue-500/20">
              
              <img src="/person.svg" alt="avator" width={100} height={100}/>
              <div className="font-zh font-bold text-base mt-4">羅如妘</div>
              <div className="font-en text-sm tracking-wider">Ru yun, Luo</div>
              <div className="flex gap-3 my-4 items-center">
                <a href="https://www.instagram.com/ruoyun1005/" className="group">
                  <div className="bg-[#FFFEFA] hover:bg-[#A7B2CC] w-[40px] h-[40px] rounded-full flex justify-center items-center transition-colors duration-300 hover:scale-110">
                    <img src="/Instagram.svg" className="w-[20px] h-[20px] transition-all duration-300 group-hover:invert group-hover:brightness-0" />
                  </div>
                </a>
                <a href="https://github.com/ruoyun1005" className="group">
                  <div className="bg-[#FFFEFA] hover:bg-[#A7B2CC] w-[40px] h-[40px] rounded-full flex justify-center items-center transition-colors duration-300 hover:scale-110">
                    <img src="/Github.svg" className="w-[20px] h-[20px] transition-all duration-300 group-hover:invert group-hover:brightness-0" />
                  </div>
                </a>
              </div>
              <SideBar />
            </div>
          <div className="w-full h-full sm:flex-1 min-w-[250px] bg-[#FBFCFE] flex flex-col justify-start items-start rounded-2xl shadow-sm shadow-blue-500/20 overflow-y-auto overflow-x-hidden">
              {children}
          </div>
          
      </div>
      </body>
    </html>
  );
}
